package com.myspace.transactionanalytics;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String transactionId;
	private java.lang.Double transactionAmount;
	private java.lang.String mcc;
	private java.lang.String transactionCountry;
	private java.lang.String customerId;
	private java.lang.String customerCountry;

	private java.lang.String customerClass;

	private java.lang.Boolean inconsistencyFlagged = true;

	private java.lang.Boolean riskFlagged;

	private java.lang.Boolean dueDiligenceFlagged;

	private java.lang.Boolean mccCodeFlagged = false;

	private java.lang.Integer customerAge;

	public Transaction() {
	}

	public java.lang.String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(java.lang.String transactionId) {
		this.transactionId = transactionId;
	}

	public java.lang.Double getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(java.lang.Double transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	public java.lang.String getMcc() {
		return this.mcc;
	}

	public void setMcc(java.lang.String mcc) {
		this.mcc = mcc;
	}

	public java.lang.String getTransactionCountry() {
		return this.transactionCountry;
	}

	public void setTransactionCountry(java.lang.String transactionCountry) {
		this.transactionCountry = transactionCountry;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getCustomerCountry() {
		return this.customerCountry;
	}

	public void setCustomerCountry(java.lang.String customerCountry) {
		this.customerCountry = customerCountry;
	}

	public java.lang.String getCustomerClass() {
		return this.customerClass;
	}

	public void setCustomerClass(java.lang.String customerClass) {
		this.customerClass = customerClass;
	}

	public java.lang.Boolean getInconsistencyFlagged() {
		return this.inconsistencyFlagged;
	}

	public void setInconsistencyFlagged(java.lang.Boolean inconsistencyFlagged) {
		this.inconsistencyFlagged = inconsistencyFlagged;
	}

	public java.lang.Boolean getRiskFlagged() {
		return this.riskFlagged;
	}

	public void setRiskFlagged(java.lang.Boolean riskFlagged) {
		this.riskFlagged = riskFlagged;
	}

	public java.lang.Boolean getDueDiligenceFlagged() {
		return this.dueDiligenceFlagged;
	}

	public void setDueDiligenceFlagged(java.lang.Boolean dueDiligenceFlagged) {
		this.dueDiligenceFlagged = dueDiligenceFlagged;
	}

	public java.lang.Boolean getMccCodeFlagged() {
		return this.mccCodeFlagged;
	}

	public void setMccCodeFlagged(java.lang.Boolean mccCodeFlagged) {
		this.mccCodeFlagged = mccCodeFlagged;
	}

	public String toString() {
		return "[ transaction:" + transactionId + ", inconsistencyFlagged:"
				+ inconsistencyFlagged
				+ ", mccCodeFlagged:" + mccCodeFlagged + "]";
	}

	public java.lang.Integer getCustomerAge() {
		return this.customerAge;
	}

	public void setCustomerAge(java.lang.Integer customerAge) {
		this.customerAge = customerAge;
	}

	public Transaction(java.lang.String transactionId,
			java.lang.Double transactionAmount, java.lang.String mcc,
			java.lang.String transactionCountry, java.lang.String customerId,
			java.lang.String customerCountry, java.lang.String customerClass,
			java.lang.Boolean inconsistencyFlagged,
			java.lang.Boolean riskFlagged,
			java.lang.Boolean dueDiligenceFlagged,
			java.lang.Boolean mccCodeFlagged, java.lang.Integer customerAge) {
		this.transactionId = transactionId;
		this.transactionAmount = transactionAmount;
		this.mcc = mcc;
		this.transactionCountry = transactionCountry;
		this.customerId = customerId;
		this.customerCountry = customerCountry;
		this.customerClass = customerClass;
		this.inconsistencyFlagged = inconsistencyFlagged;
		this.riskFlagged = riskFlagged;
		this.dueDiligenceFlagged = dueDiligenceFlagged;
		this.mccCodeFlagged = mccCodeFlagged;
		this.customerAge = customerAge;
	}

}